# Hardware configuration for example-desktop
# This file is typically generated by nixos-generate-config
# Replace this with your actual hardware configuration

{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Example hardware configuration - REPLACE WITH YOUR ACTUAL CONFIG
  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ]; # or "kvm-amd" for AMD
    extraModulePackages = [ ];
  };

  # Filesystem configuration - EXAMPLE ONLY
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/YOUR-ROOT-UUID";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/YOUR-BOOT-UUID";
      fsType = "vfat";
    };

  # Swap configuration - EXAMPLE ONLY
  swapDevices = [
    { device = "/dev/disk/by-uuid/YOUR-SWAP-UUID"; }
  ];

  # Network hardware
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Hardware specific options
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
