# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# Disable line length check (MD013) for compatibility with various screen sizes
MD013: false
# Allow inline HTML for better documentation formatting
MD033: false
# Allow duplicate headers in different sections
MD024:
  allow_different_nesting: true
# Allow bare URLs for simplicity in documentation
MD034: false
# Trailing punctuation in headers
MD026:
  punctuation: ".,;:!"
